name: "HN news scraper trigger"
on:
  schedule:
    - cron:  '5 * * * *'    # At every 5 minute

jobs:
  trigger-scrape:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering"
      - run: curl https://hn-service.onrender.com/api/v1/cron/trigger/
      - run: echo "Done"